- hosts: master,slaves,clients
  tasks:
    - copy:
        src: '../hadoop/hadoop_hosts'
        dest: '/etc/hosts'
    - service:
        name: firewalld
        state: stopped
        enabled: yes
    - command: "setenforce 0"

  # - copy:
  #     src: '../hadoop/jdk-8u171-linux-x64.rpm'
  #     dest: '/root/'
#    - copy:
#       src: '../hadoop/hadoop-1.2.1-1.x86_64.rpm'
#        dest: '/root/'

  #  - command: 'rpm -ivh  /root/jdk-8u171-linux-x64.rpm'

#    - lineinfile:
#        path: '/root/.bashrc'
#        line: 'export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/'

#    - lineinfile:
#       path: '/root/.bashrc'
#        line: 'export PATH=/usr/java/jdk1.8.0_171-amd64//bin/:$PATH'
    - copy:
        src: '../hadoop/.bashrc'
        dest: '/root/.bashrc'

 #   - command: 'rpm -ivh  /root/hadoop-1.2.1-1.x86_64.rpm --force'
